### ISSUE TITLE
cannot import graph_tool.draw

### ISSUE THREAD

**Issue by wxl1351641822** [conda-forge/graph-tool-feedstock#48]
my version==2.29,can you help me?
>>> import graph_tool.draw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/graph_tool/draw/__init__.py", line 875, in <module>
    from . cairo_draw import graph_draw, cairo_draw, get_hierarchy_control_points, default_cm
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py", line 1489, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/data/miniconda3/envs/openea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/data/miniconda3/envs/openea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/gi/overrides/Gdk.py", line 83, in <module>
    Color = override(Color)
  File "/data/miniconda3/envs/openea/lib/python3.6/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

**Comment by stuarteberg** [comment]
Sorry, I'm not sure why it's not working.  From your error message, it appears that there is some incompatibility with GDK.

I was going to ask if you could upgrade to a newer version of graph-tool, but I notice that [the OpenEA installation instructions claim that only 2.29 works with their software.][1]

[1]: https://github.com/nju-websoft/OpenEA#installation

Do you need drawing support?  If not, then perhaps you can avoid GDK altogether.  As it happens, early versions of the graph-tool conda package did not support drawing, so they don't include GDK as a dependency.  Perhaps you can try installing that early version by explicitly specifying the build number (`graph-tool=2.29=1`) as shown here:

```bash
conda create -n openea python=3.6
conda activate openea
conda install tensorflow-gpu==1.12
conda install -c conda-forge graph-tool=2.29=1
```

The goal here is to create an environment with graph-tool 2.29, but WITHOUT gdk installed.

**Comment by wxl1351641822** [comment]
well……I test install it again.but I failed.I need graph-tool.draw
conda install -c https://conda.anaconda.org/conda-forge graph-tool
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by wxl1351641822** [comment]
Can I install graph-tool by tar.bz2?how can I do?

**Comment by stuarteberg** [comment]
I think there is a command-line option to install using the tarball, but then all dependencies would be missing.  Are you able to use the latest version of graph-tool?

```bash
conda create -n gt -c conda-forge 'graph-tool>=2.37'
conda activate graph-tool
python -c "import graph_tool.all as gt"
```

**Comment by wxl1351641822** [comment]
It dosen't work.Can you give me your conda-forge url to download?
C:\Users\wxl>docker history --format tiagopeixoto/graph-tool
"docker history" requires exactly 1 argument.
See 'docker history --help'.

Usage:  docker history [OPTIONS] IMAGE

Show the history of an image

C:\Users\wxl>conda create -n gt -c conda-forge 'graph-tool>=2.37'

PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



C:\Users\wxl>conda activate graph-tool
Could not find conda environment: graph-tool
You can list all discoverable environments with `conda info --envs`.

**Comment by stuarteberg** [comment]
It appears you're attempting to install graph-tool on a Windows machine.  That won't work, since graph-tool only supports Linux and Mac.

**Comment by stuarteberg** [comment]
FWIW, your original issue was also encountered by another user, in #63.  That user found a solution to the issue, which is to make sure you're obtaining all dependencies from `conda-forge` when possible.
